sudo: required
services:
  - docker

before_install:
  - docker build -t emugisha/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true emugisha/react-test npm test

after_success:
  - docker build -t emugisha/complex-client ./client 
  - docker build -t emugisha/complex-nginx ./nginx
  - docker build -t emugisha/complex-server ./server
  - docker build -t emugisha/complex-worker ./worker

# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --passowrd-stdin
# Push images to docker hub
  - docker push emugisha/complex-client
  - docker push emugisha/complex-nginx
  - docker push emugisha/complex-server
  - docker push emugisha/complex-worker